FROM microsoft/dotnet:2.1-sdk-bionic

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y mono-devel ca-certificates-mono nuget openjdk-8-jdk \
    && rm -rf /var/lib/apt/lists/* /tmp/*